TYPES: BEGIN OF e070use,
         username TYPE c LENGTH 12,
         trfunction TYPE c LENGTH 1,
         category TYPE c LENGTH 4,
         client TYPE c LENGTH 3,
         fixtype TYPE c LENGTH 1,
         ordernum TYPE c LENGTH 20,
         tasknum TYPE c LENGTH 20,
         validity TYPE d,
       END OF e070use.