
TYPES: BEGIN OF progdir,
 name    TYPE c LENGTH 1,
 state   TYPE c LENGTH 1,
 sqlx    TYPE c LENGTH 1,
 edtx    TYPE c LENGTH 1,
 varcl   TYPE c LENGTH 1,
 dbapl   TYPE c LENGTH 1,
 dbna    TYPE c LENGTH 1,
 clas    TYPE c LENGTH 1,
 type    TYPE c LENGTH 1,
 occurs  TYPE c LENGTH 1,
 subc    TYPE c LENGTH 1,
 appl    TYPE c LENGTH 1,
 secu    TYPE c LENGTH 1,
 cnam    TYPE c LENGTH 1,
 cdat    TYPE c LENGTH 1,
 unam    TYPE c LENGTH 1,
 udat    TYPE c LENGTH 1,
 vern    TYPE c LENGTH 1,
 levl    TYPE c LENGTH 1,
 rstat   TYPE c LENGTH 1,
 rmand   TYPE c LENGTH 1,
 rload   TYPE c LENGTH 1,
 fixpt   TYPE c LENGTH 1,
 sset    TYPE c LENGTH 1,
 sdate   TYPE c LENGTH 1,
 stime   TYPE c LENGTH 1,
 idate   TYPE c LENGTH 1,
 itime   TYPE c LENGTH 1,
 ldbname TYPE c LENGTH 1,
 uccheck TYPE c LENGTH 1,
END OF progdir.